catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다. catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).catch(  
    e => console.log(e)); // Error: rejected
```

catch 메서드는 then(undefined, onRejected)과 동일하게 동작한다. 따라서 then 메서드와 마찬가지로 언제나 프로미스를 반환한다.

```javascript
new Promise((_, reject) => reject(new Error('rejected'))).then(undefined,  
    e => console.log(e)); // Error: rejected
```